# Generated by Django 4.0.4 on 2022-05-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=256)),
                ('adresse', models.CharField(max_length=256)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('etat', models.CharField(max_length=20)),
                ('note', models.FloatField()),
                ('heure_ouverture', models.DurationField()),
                ('heure_fermeture', models.DurationField()),
                ('tarif', models.FloatField()),
                ('occupation', models.FloatField()),
                ('nombre_places', models.IntegerField()),
                ('photo', models.CharField(max_length=512)),
            ],
        ),
    ]
