# Generated by Django 4.0.4 on 2022-05-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('adresse', models.CharField(max_length=256)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ouvert', models.BooleanField()),
                ('note', models.FloatField()),
                ('horaire_debut', models.DurationField()),
                ('horaire_fin', models.DurationField()),
                ('prix', models.FloatField()),
                ('taux_occupation', models.FloatField()),
                ('nombre_places', models.IntegerField()),
            ],
        ),
    ]
