# Generated by Django 4.0.4 on 2022-05-20 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parkings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=256)),
                ('adresse', models.CharField(max_length=256)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('etat', models.CharField(max_length=20)),
                ('note', models.FloatField()),
                ('heure_ouverture', models.DurationField()),
                ('heure_fermeture', models.DurationField()),
                ('tarif', models.FloatField()),
                ('occupation', models.FloatField()),
                ('nombre_places', models.IntegerField()),
                ('photo', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=10)),
                ('mdp', models.CharField(max_length=256)),
                ('photo', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('h_entree', models.DateTimeField()),
                ('h_sortie', models.DateTimeField()),
                ('code_QR', models.CharField(max_length=512)),
                ('num_place', models.CharField(max_length=10)),
                ('parking_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.parkings')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.utilisateur')),
            ],
        ),
    ]
